### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hindol1999** [MOSAICS-NIH/MOSAICS#1]
Hi,
This seems to be a wonderful tool for lipid calculation. But during the usage of MOSAICS, I noticed zcoord_mpi and membrane_thickness_mpi executables are not created. During the installation, there were some error messages. I am attaching the screenshots here. It would be great if you could suggest something to overcome the issue. 
Thanks,
Hindol

![Screenshot 2023-04-04 143932](https://user-images.githubusercontent.com/106383682/229746465-61ef17bd-c8f6-4d41-809b-abfce47d0d24.png)
![Screenshot 2023-04-04 144132](https://user-images.githubusercontent.com/106383682/229746481-638751d1-a013-4004-b5e5-f64cb8ab15f8.png)

**Comment by giacomofiorin** [comment]
@hindol1999 This should be fixed in #2.
