### ISSUE TITLE
Mean squared displacement (MSD)

### ISSUE THREAD

**Issue by BadelBF** [MOSAICS-NIH/MOSAICS#6]
Hi Nathan,
I'm trying to measure the mean squared displacement (MSD) but the Lipids aren't recognized by `lipid_msd_mpi`. I tried using the cards as described in the manual by the Figure 4-6.

```
There are  0 lipid types in the selected leaflet (both) as summarized below: 
 index       type       count 

You have selected (-crd) the following lipid types: 
 index       type       count 

     0       POPE           0 
     1       POPG           0 
     2       PVCL           0
```

I found the same Issue when applying `z_coord_mpi`, but was solved adding the biomolecules by the tag -lf_prm. I'm tried the same way, but there is no -lf_prm for `lipid_msd_mpi` :
```
 $ lipid_msd_mpi -h 

Description: Lipid MSD is an analysis tool designed to compute the mean square displacement for lipids in the xy plane as a 
function of time. This should yield a straight line where the slope is proportional to the diffusion coeficient. 

        To use this program please enter the following command line options. 

        -traj   R    S    Input trajectory file (xtc, trr, pdb, gro)
        -ref    R    S    Refference file (pdb, gro)
        -o      O    S    Output trajectory file (xtc, trr, pdb, gro)
        -stride O    I    Read every 'stride' frame
        -b      O    I    Skip frames before this number
        -e      O    I    Skip frames after this number
        -lsq    O    S    Index for lsq fitting (ndx)
        -lsq_d  O    I    Dimension for lsq fitting (3:x,y,z 2:x,y)
        -lsq_r  O    I    Reference structure for lsq fitting (0:ref 1:first_frame)
        -crd    R    S    Selection card (crd)
        -msd    R    S    Output data file with MSD data (dat)
        -dt     R    F    Time between analyzed frames (accounting for stride, ps)
        -h      O    -    print help options__    
```
Finally, I tried to add the head and tail of the lipid on `leaflet_finder.h` file, but not worked.
I reaaly appreciate your help.
All the best.

**Comment by bernhardtna** [comment]
Hi BadelBF. Thank you for reaching out for help. From reading your description, I believe you were on the right track when attempting to add the lipid types to the leaflet finder with the -lf_param tag. This option was intended to be available for the Lipid MSD program like it is with Z-coord, and I have now added this option to Lipid MSD. You should thus be able to complete your analysis if you install the latest version. Hope this helps.
